apiVersion: v1
kind: Service
metadata:
  name: kubeserviceappv1
spec:
  selector:
    app: kubeapp
  ports:
    - port: 8080
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
        - name: kubecontainer
          image: sebamateos/aplicativo:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb+srv://sebitamateos1080:EdQz5XRClkLkwVo7@sebamateos.y8yajgz.mongodb.net/
          imagePullPolicy: Always
